# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\wolfeite\projectPy\frame\socketserver\gui\UI\UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI(object):
    def setupUi(self, UI):
        UI.setObjectName("UI")
        UI.resize(575, 701)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\wolfeite\\projectPy\\frame\\socketserver\\gui\\UI\\Data/Assets/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UI.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(UI)
        self.centralWidget.setObjectName("centralWidget")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(210, 10, 151, 21))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("E:\\wolfeite\\projectPy\\frame\\socketserver\\gui\\UI\\Data/Assets/logo.png"))
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 271, 301))
        self.groupBox.setObjectName("groupBox")
        self.links = QtWidgets.QTextEdit(self.groupBox)
        self.links.setGeometry(QtCore.QRect(10, 20, 251, 241))
        self.links.setObjectName("links")
        self.detect = QtWidgets.QPushButton(self.groupBox)
        self.detect.setGeometry(QtCore.QRect(10, 270, 75, 23))
        self.detect.setObjectName("detect")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 40, 231, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.ip = QtWidgets.QLineEdit(self.groupBox_2)
        self.ip.setGeometry(QtCore.QRect(50, 20, 151, 20))
        self.ip.setObjectName("ip")
        self.port = QtWidgets.QLineEdit(self.groupBox_2)
        self.port.setGeometry(QtCore.QRect(50, 50, 151, 20))
        self.port.setObjectName("port")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 54, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 54, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 31, 21))
        self.label_3.setObjectName("label_3")
        self.loop_single = QtWidgets.QCheckBox(self.groupBox_2)
        self.loop_single.setGeometry(QtCore.QRect(150, 80, 71, 21))
        self.loop_single.setObjectName("loop_single")
        self.interval_single = QtWidgets.QLineEdit(self.groupBox_2)
        self.interval_single.setGeometry(QtCore.QRect(50, 80, 61, 21))
        self.interval_single.setObjectName("interval_single")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 31, 21))
        self.label_5.setObjectName("label_5")
        self.context_single = QtWidgets.QLineEdit(self.groupBox_2)
        self.context_single.setGeometry(QtCore.QRect(50, 110, 121, 21))
        self.context_single.setObjectName("context_single")
        self.send_single = QtWidgets.QPushButton(self.groupBox_2)
        self.send_single.setGeometry(QtCore.QRect(180, 110, 41, 23))
        self.send_single.setObjectName("send_single")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 150, 31, 21))
        self.label_7.setObjectName("label_7")
        self.counts_single = QtWidgets.QLabel(self.groupBox_2)
        self.counts_single.setGeometry(QtCore.QRect(50, 150, 81, 21))
        self.counts_single.setObjectName("counts_single")
        self.stop_single = QtWidgets.QPushButton(self.groupBox_2)
        self.stop_single.setGeometry(QtCore.QRect(130, 150, 41, 23))
        self.stop_single.setObjectName("stop_single")
        self.clear_single = QtWidgets.QPushButton(self.groupBox_2)
        self.clear_single.setGeometry(QtCore.QRect(180, 150, 41, 23))
        self.clear_single.setObjectName("clear_single")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(120, 80, 31, 21))
        self.label_11.setObjectName("label_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 230, 231, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.context_all = QtWidgets.QLineEdit(self.groupBox_3)
        self.context_all.setGeometry(QtCore.QRect(40, 50, 131, 21))
        self.context_all.setObjectName("context_all")
        self.send_all = QtWidgets.QPushButton(self.groupBox_3)
        self.send_all.setGeometry(QtCore.QRect(180, 50, 41, 23))
        self.send_all.setObjectName("send_all")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.label_4.setObjectName("label_4")
        self.interval_all = QtWidgets.QLineEdit(self.groupBox_3)
        self.interval_all.setGeometry(QtCore.QRect(40, 20, 61, 21))
        self.interval_all.setObjectName("interval_all")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 31, 21))
        self.label_9.setObjectName("label_9")
        self.loop_all = QtWidgets.QCheckBox(self.groupBox_3)
        self.loop_all.setGeometry(QtCore.QRect(150, 20, 71, 21))
        self.loop_all.setObjectName("loop_all")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 31, 41))
        self.label_10.setObjectName("label_10")
        self.counts_all = QtWidgets.QLabel(self.groupBox_3)
        self.counts_all.setGeometry(QtCore.QRect(50, 80, 101, 21))
        self.counts_all.setObjectName("counts_all")
        self.clear_all = QtWidgets.QPushButton(self.groupBox_3)
        self.clear_all.setGeometry(QtCore.QRect(180, 80, 41, 21))
        self.clear_all.setObjectName("clear_all")
        self.stop_all = QtWidgets.QPushButton(self.groupBox_3)
        self.stop_all.setGeometry(QtCore.QRect(130, 80, 41, 21))
        self.stop_all.setObjectName("stop_all")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(110, 20, 31, 21))
        self.label_8.setObjectName("label_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 360, 271, 311))
        self.groupBox_4.setObjectName("groupBox_4")
        self.receive = QtWidgets.QTextEdit(self.groupBox_4)
        self.receive.setGeometry(QtCore.QRect(10, 20, 251, 251))
        self.receive.setObjectName("receive")
        self.clear_recv = QtWidgets.QPushButton(self.groupBox_4)
        self.clear_recv.setGeometry(QtCore.QRect(10, 280, 75, 23))
        self.clear_recv.setObjectName("clear_recv")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 360, 231, 311))
        self.groupBox_5.setObjectName("groupBox_5")
        self.counts_recv = QtWidgets.QTextEdit(self.groupBox_5)
        self.counts_recv.setGeometry(QtCore.QRect(20, 20, 201, 251))
        self.counts_recv.setObjectName("counts_recv")
        self.aggregate = QtWidgets.QPushButton(self.groupBox_5)
        self.aggregate.setGeometry(QtCore.QRect(20, 280, 75, 23))
        self.aggregate.setObjectName("aggregate")
        self.clear_counts_recv = QtWidgets.QPushButton(self.groupBox_5)
        self.clear_counts_recv.setGeometry(QtCore.QRect(150, 280, 71, 23))
        self.clear_counts_recv.setObjectName("clear_counts_recv")
        UI.setCentralWidget(self.centralWidget)

        self.retranslateUi(UI)
        QtCore.QMetaObject.connectSlotsByName(UI)

    def retranslateUi(self, UI):
        _translate = QtCore.QCoreApplication.translate
        UI.setWindowTitle(_translate("UI", "中控连接中心"))
        self.groupBox.setTitle(_translate("UI", "所连设备"))
        self.detect.setText(_translate("UI", "检测"))
        self.groupBox_2.setTitle(_translate("UI", "单发送测试"))
        self.label.setText(_translate("UI", "IP"))
        self.label_2.setText(_translate("UI", "端口"))
        self.label_3.setText(_translate("UI", "内容"))
        self.loop_single.setText(_translate("UI", "循环发送"))
        self.interval_single.setText(_translate("UI", "1"))
        self.label_5.setText(_translate("UI", "间隔"))
        self.send_single.setText(_translate("UI", "发送"))
        self.label_7.setText(_translate("UI", "次数："))
        self.counts_single.setText(_translate("UI", "0"))
        self.stop_single.setText(_translate("UI", "停止"))
        self.clear_single.setText(_translate("UI", "清理"))
        self.label_11.setText(_translate("UI", "ms"))
        self.groupBox_3.setTitle(_translate("UI", "群发测试"))
        self.send_all.setText(_translate("UI", "发送"))
        self.label_4.setText(_translate("UI", "内容"))
        self.interval_all.setText(_translate("UI", "1"))
        self.label_9.setText(_translate("UI", "间隔"))
        self.loop_all.setText(_translate("UI", "循环发送"))
        self.label_10.setText(_translate("UI", "次数："))
        self.counts_all.setText(_translate("UI", "0"))
        self.clear_all.setText(_translate("UI", "清理"))
        self.stop_all.setText(_translate("UI", "停止"))
        self.label_8.setText(_translate("UI", "ms"))
        self.groupBox_4.setTitle(_translate("UI", "收到信息"))
        self.clear_recv.setText(_translate("UI", "清理"))
        self.groupBox_5.setTitle(_translate("UI", "信息统计"))
        self.counts_recv.setHtml(_translate("UI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">点击统计收到的信息</span></p></body></html>"))
        self.aggregate.setText(_translate("UI", "统计"))
        self.clear_counts_recv.setText(_translate("UI", "清理"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UI = QtWidgets.QMainWindow()
    ui = Ui_UI()
    ui.setupUi(UI)
    UI.show()
    sys.exit(app.exec_())
