# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\LOVTeam\IOT\Su3\UI\UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UI(object):
    def setupUi(self, UI):
        UI.setObjectName("UI")
        UI.resize(417, 447)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Data/Assets/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UI.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(UI)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 381, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(200, 20, 151, 21))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Data/Assets/logo.png"))
        self.label_6.setObjectName("label_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_3.setGeometry(QtCore.QRect(20, 50, 331, 321))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setEnabled(True)
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 312, 900))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(0, 900))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.txtMember = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.txtMember.setGeometry(QtCore.QRect(20, 10, 281, 811))
        self.txtMember.setText("")
        self.txtMember.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtMember.setObjectName("txtMember")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_licence = QtWidgets.QWidget()
        self.tab_licence.setObjectName("tab_licence")
        self.label_8 = QtWidgets.QLabel(self.tab_licence)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.inputCode = QtWidgets.QPlainTextEdit(self.tab_licence)
        self.inputCode.setGeometry(QtCore.QRect(10, 30, 351, 251))
        self.inputCode.setUndoRedoEnabled(True)
        self.inputCode.setObjectName("inputCode")
        self.btnLicence = QtWidgets.QPushButton(self.tab_licence)
        self.btnLicence.setGeometry(QtCore.QRect(180, 360, 75, 23))
        self.btnLicence.setObjectName("btnLicence")
        self.txtLicenceID = QtWidgets.QLabel(self.tab_licence)
        self.txtLicenceID.setGeometry(QtCore.QRect(20, 300, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtLicenceID.setFont(font)
        self.txtLicenceID.setObjectName("txtLicenceID")
        self.txtLicenceDate = QtWidgets.QLabel(self.tab_licence)
        self.txtLicenceDate.setGeometry(QtCore.QRect(20, 330, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtLicenceDate.setFont(font)
        self.txtLicenceDate.setObjectName("txtLicenceDate")
        self.btnWebLicence = QtWidgets.QPushButton(self.tab_licence)
        self.btnWebLicence.setGeometry(QtCore.QRect(280, 360, 75, 23))
        self.btnWebLicence.setObjectName("btnWebLicence")
        self.tabWidget.addTab(self.tab_licence, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_8)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 50, 351, 141))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 332, 2000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 2000))
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(400, 200))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.txtApiPara7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.txtApiPara7.setGeometry(QtCore.QRect(10, 200, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtApiPara7.setFont(font)
        self.txtApiPara7.setObjectName("txtApiPara7")
        self.inputPara2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.inputPara2.setGeometry(QtCore.QRect(100, 50, 221, 20))
        self.inputPara2.setText("")
        self.inputPara2.setObjectName("inputPara2")
        self.inputPara4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.inputPara4.setGeometry(QtCore.QRect(100, 110, 221, 20))
        self.inputPara4.setText("")
        self.inputPara4.setObjectName("inputPara4")
        self.txtApiPara4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.txtApiPara4.setGeometry(QtCore.QRect(10, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtApiPara4.setFont(font)
        self.txtApiPara4.setObjectName("txtApiPara4")
        self.txtApiPara2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.txtApiPara2.setGeometry(QtCore.QRect(10, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtApiPara2.setFont(font)
        self.txtApiPara2.setObjectName("txtApiPara2")
        self.inputPara1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.inputPara1.setGeometry(QtCore.QRect(100, 20, 221, 20))
        self.inputPara1.setText("")
        self.inputPara1.setObjectName("inputPara1")
        self.inputPara6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.inputPara6.setGeometry(QtCore.QRect(100, 170, 221, 20))
        self.inputPara6.setText("")
        self.inputPara6.setObjectName("inputPara6")
        self.inputPara5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.inputPara5.setGeometry(QtCore.QRect(100, 140, 221, 20))
        self.inputPara5.setText("")
        self.inputPara5.setObjectName("inputPara5")
        self.txtApiPara5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.txtApiPara5.setGeometry(QtCore.QRect(10, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtApiPara5.setFont(font)
        self.txtApiPara5.setObjectName("txtApiPara5")
        self.txtApiPara6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.txtApiPara6.setGeometry(QtCore.QRect(10, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtApiPara6.setFont(font)
        self.txtApiPara6.setObjectName("txtApiPara6")
        self.inputPara3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.inputPara3.setGeometry(QtCore.QRect(100, 80, 221, 20))
        self.inputPara3.setText("")
        self.inputPara3.setObjectName("inputPara3")
        self.txtApiPara3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.txtApiPara3.setGeometry(QtCore.QRect(10, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtApiPara3.setFont(font)
        self.txtApiPara3.setObjectName("txtApiPara3")
        self.inputPara7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.inputPara7.setGeometry(QtCore.QRect(100, 200, 221, 20))
        self.inputPara7.setText("")
        self.inputPara7.setObjectName("inputPara7")
        self.txtApiPara1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.txtApiPara1.setGeometry(QtCore.QRect(10, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtApiPara1.setFont(font)
        self.txtApiPara1.setObjectName("txtApiPara1")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.btnTestApi = QtWidgets.QPushButton(self.tab_8)
        self.btnTestApi.setGeometry(QtCore.QRect(290, 320, 75, 23))
        self.btnTestApi.setObjectName("btnTestApi")
        self.label_41 = QtWidgets.QLabel(self.tab_8)
        self.label_41.setGeometry(QtCore.QRect(10, 200, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_34 = QtWidgets.QLabel(self.tab_8)
        self.label_34.setGeometry(QtCore.QRect(10, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.selectApi = QtWidgets.QComboBox(self.tab_8)
        self.selectApi.setGeometry(QtCore.QRect(50, 20, 221, 22))
        self.selectApi.setObjectName("selectApi")
        self.scrollArea_8 = QtWidgets.QScrollArea(self.tab_8)
        self.scrollArea_8.setGeometry(QtCore.QRect(10, 220, 351, 91))
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 332, 2000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_8.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_8.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_8.setMinimumSize(QtCore.QSize(0, 2000))
        self.scrollAreaWidgetContents_8.setMaximumSize(QtCore.QSize(332, 200))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.txtApiInfo = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.txtApiInfo.setGeometry(QtCore.QRect(0, 0, 331, 2000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtApiInfo.sizePolicy().hasHeightForWidth())
        self.txtApiInfo.setSizePolicy(sizePolicy)
        self.txtApiInfo.setMinimumSize(QtCore.QSize(0, 2000))
        self.txtApiInfo.setText("")
        self.txtApiInfo.setScaledContents(False)
        self.txtApiInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtApiInfo.setWordWrap(True)
        self.txtApiInfo.setObjectName("txtApiInfo")
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        self.tabWidget.addTab(self.tab_8, "")
        UI.setCentralWidget(self.centralWidget)

        self.retranslateUi(UI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UI)

    def retranslateUi(self, UI):
        _translate = QtCore.QCoreApplication.translate
        UI.setWindowTitle(_translate("UI", "中控连接中心"))
        self.label_10.setText(_translate("UI", "设备连接状态："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UI", "设备连接"))
        self.label_8.setText(_translate("UI", "激活码"))
        self.btnLicence.setText(_translate("UI", "激活"))
        self.txtLicenceID.setText(_translate("UI", "设备ID:"))
        self.txtLicenceDate.setText(_translate("UI", "过期时间:"))
        self.btnWebLicence.setText(_translate("UI", "线上激活"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_licence), _translate("UI", "授权"))
        self.txtApiPara7.setText(_translate("UI", "Para7:"))
        self.txtApiPara4.setText(_translate("UI", "Para4:"))
        self.txtApiPara2.setText(_translate("UI", "Para2:"))
        self.txtApiPara5.setText(_translate("UI", "Para5:"))
        self.txtApiPara6.setText(_translate("UI", "Para6:"))
        self.txtApiPara3.setText(_translate("UI", "Para3:"))
        self.txtApiPara1.setText(_translate("UI", "Para1:"))
        self.btnTestApi.setText(_translate("UI", "测试"))
        self.label_41.setText(_translate("UI", "说明 / 回馈 :"))
        self.label_34.setText(_translate("UI", "API:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("UI", "API"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UI = QtWidgets.QMainWindow()
    ui = Ui_UI()
    ui.setupUi(UI)
    UI.show()
    sys.exit(app.exec_())

